language: node_js
node_js:
  - "node"
  - "lts/*"
jobs:
  include:
    - stage: Release
      if: branch = master
      name: "Build"
      script: yarn build
    - script: echo "publish to npm ..."
      name: "Publish to NPM"
      deploy:
        provider: npm
        api_token: $NPM_API_KEY
        edge: true