language: node_js
node_js:
  - "8"
jobs:
  include:
    - stage: Test
      node_js: "lts/*"
      script: yarn test
    - stage: Release
      if: branch = master
      node_js: "8"
      script: yarn build
      deploy:
        provider: npm
        api_token: $NPM_API_KEY
        edge: true