language: node_js
node_js:
  - "8"
  - "10"
  - "lts/*"
jobs:
  include:
    - stage: Test
      script: yarn test
    - stage: Build
      script: yarn build
      branches:
        only:
          - master
    - stage: Deploy to npm
      script: echo "Deploying to npm ..."
      branches:
        only:
          - master
      deploy:
        provider: npm
        api_token: $NPM_API_KEY
        edge: true