language: node_js
node_js:
  - "node"
  - "lts/*"
jobs:
  include:
    - stage: Test
      script: yarn test
    - stage: Build
      if: branch = master
      script: yarn build
    - stage: Deploy to npm
      if: branch = master
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_token: $NPM_API_KEY
        edge: true